In [367]:
'''1. Write a python program which searches all the product under a particular product from www.amazon.in.
The product to be searched will be taken as input from user. For e.g. If user input is ‘guitar’. Then search
for guitars.
2. In the above question, now scrape the following details of each product listed in first 3 pages of your
search results and save it in a data frame and csv. In case if any product has less than 3 pages in search
results then scrape all the products available under that product name. Details to be scraped are: "Brand
Name", "Name of the Product", "Price", "Return/Exchange", "Expected Delivery", "Availability" and
“Product URL”. In case, if any of the details are missing for any of the product then replace it by “-“.'''

import pandas as pd
import selenium 
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
import time
from selenium.common.exceptions import NoSuchElementException

In [414]:
driver= webdriver.Chrome(r"C:\Users\amang\chromedriver_win32\chromedriver.exe")

In [415]:
url= "https://www.amazon.in/"
driver.get(url)

In [378]:
prod= input("Enter the product you want to search for: ")

Enter the product you want to search for: guitar

In [416]:
# input in search bar
inp=driver.find_element("xpath","/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[2]/div[1]/input")
inp.send_keys(prod)

In [417]:
srch=driver.find_element("xpath","/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[3]/div/span/input")
srch.click()

In [428]:

nxt=driver.find_element('xpath','//a[@class="s-pagination-item s-pagination-button"]')
p2=(nxt.get_attribute("href"))
print(p2)
nxt.click()
time.sleep(3)
page1=driver.find_element("xpath",'//a[@class="s-pagination-item s-pagination-previous s-pagination-button s-pagination-separator"]')
p1=(page1.get_attribute("href"))
time.sleep(2)
driver.get(p1)
'''lnk=driver.find_elements("xpath",'//a[@class="a-link-normal s-no-outline"]')
#lnk.click()
for i in lnk:
    link.append(i.get_attribute("href"))'''

https://www.amazon.in/s?k=guitar&page=2&qid=1658313530&ref=sr_pg_2

'lnk=driver.find_elements("xpath",\'//a[@class="a-link-normal s-no-outline"]\')\n#lnk.click()\nfor i in lnk:\n    link.append(i.get_attribute("href"))'

In [438]:
link=[]
brand=[]
name=[]
price=[]
returnable=[]
delivery=[]
avail=[]
p=1
j=0

In [439]:
while p<=3:
    lnk=driver.find_elements("xpath",'//a[@class="a-link-normal s-no-outline"]')
#lnk.click()
    for i in lnk:
        link.append(i.get_attribute("href"))
    print("Starting.......")
    print("-~-"*20)
    while j< len(link):
        driver.get(link[j])
        time.sleep(3)
        z=[]
        e=[]
        print("getting details from product no- ",j)
        j+=1
        

#Company
        com=driver.find_elements('xpath','//a[@class="a-link-normal"]')
        for i in com:
            z.append(i.text.split())
        while (e in z):
            z.remove(e) #remove empty lists from z
    
        for i in range (0,len(z)):
            if ("Visit" in z[i][0]) or ("Brand" in z[i][0]):
                ind=i

        try:
            brand.append(z[ind][2:-1])
        except:
            brand.append(" ".join(z[ind][1:]))
        
#Product name
        pro=driver.find_element('xpath','//span[@class="a-size-large product-title-word-break"]')
        name.append(pro.text)

#price
        try:
            prc= driver.find_element('xpath','//span[@class="a-price a-text-price a-size-medium apexPriceToPay" or @class="a-price aok-align-center reinventPricePriceToPayMargin priceToPay"]')
            price.append(prc.text.split("\n")[0])
        
        except NoSuchElementException:
            price.append("-")
        
#Return/exchange
        rtrn= driver.find_elements('xpath','//a[@class="a-size-small a-link-normal a-text-normal"]')
        r=[]
        for i in rtrn:
            r.append(i.text.split())
    
        for k in range(0,len(r)):
            #print("inside loop",k)
            if ("Replacement" in r[k][-1]) or ("Returnable" in r[k][-1]):
                #print("found")
                ind=k
                returnable.append(" ".join(r[ind]))
                break
    
#delivery
        dlvry= driver.find_element('xpath','//span[@class="a-text-bold"]')
        delivery.append(dlvry.text)
    
#availability
        try:
            avl=driver.find_element('xpath','//span[@class="a-size-medium a-color-success"]')
            avail.append(avl.text)
            #time.sleep(2)
    
        except NoSuchElementException:
            avail.append("-")
            #time.sleep(3)
    print("completed page no ",p)
    print("-~-"*20)
    
#Moving to page 1
#srch=driver.find_element("xpath","/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[3]/div/span/input")
 #   srch.click()

#Next page
    if p==1:
        driver.get(p1)
        time.sleep(3)
    elif p==2:
        driver.get(p2)
        time.sleep(3)
    nxt=driver.find_elements('xpath','//a[@class="s-pagination-item s-pagination-button"]')
    if p<3:
        print("\nmoving to page no ",p+1)
    p+=1
    n=str(p)
#print(n)
    for i in nxt:
        #print(i.text)
        if i.text==n:
            i.click()
            break
    time.sleep(3)

Starting.......
-~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~-
getting details from product no-  0
getting details from product no-  1
getting details from product no-  2
getting details from product no-  3
getting details from product no-  4
getting details from product no-  5
getting details from product no-  6
getting details from product no-  7
getting details from product no-  8
getting details from product no-  9
getting details from product no-  10
getting details from product no-  11
getting details from product no-  12
getting details from product no-  13
getting details from product no-  14
getting details from product no-  15
getting details from product no-  16
getting details from product no-  17
getting details from product no-  18
getting details from product no-  19
getting details from product no-  20
getting details from product no-  21
getting details from product no-  22
completed page no  1
-~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~-

moving to page no  2
Starting.......
-~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~-
getting details from product no-  23
getting details from product no-  24
getting details from product no-  25
getting details from product no-  26
getting details from product no-  27
getting details from product no-  28
getting details from product no-  29
getting details from product no-  30
getting details from product no-  31
getting details from product no-  32
getting details from product no-  33
getting details from product no-  34
getting details from product no-  35
getting details from product no-  36
getting details from product no-  37
getting details from product no-  38
getting details from product no-  39
getting details from product no-  40
getting details from product no-  41
getting details from product no-  42
getting details from product no-  43
getting details from product no-  44
getting details from product no-  45
getting details from product no-  46
getting details from product no-  47
getting details from product no-  48
getting details from product no-  49
getting details from product no-  50
getting details from product no-  51
getting details from product no-  52
getting details from product no-  53
getting details from product no-  54
getting details from product no-  55
getting details from product no-  56
getting details from product no-  57
getting details from product no-  58
getting details from product no-  59
getting details from product no-  60
getting details from product no-  61
getting details from product no-  62
getting details from product no-  63
getting details from product no-  64
getting details from product no-  65
getting details from product no-  66
getting details from product no-  67
getting details from product no-  68
getting details from product no-  69
getting details from product no-  70
getting details from product no-  71
getting details from product no-  72
getting details from product no-  73
getting details from product no-  74
getting details from product no-  75
getting details from product no-  76
getting details from product no-  77
getting details from product no-  78
getting details from product no-  79
getting details from product no-  80
getting details from product no-  81
getting details from product no-  82
completed page no  2
-~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~-

moving to page no  3
Starting.......
-~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~-
getting details from product no-  83
getting details from product no-  84
getting details from product no-  85
getting details from product no-  86
getting details from product no-  87
getting details from product no-  88
getting details from product no-  89
getting details from product no-  90
getting details from product no-  91
getting details from product no-  92
getting details from product no-  93
getting details from product no-  94
getting details from product no-  95
getting details from product no-  96
getting details from product no-  97
getting details from product no-  98
getting details from product no-  99
getting details from product no-  100
getting details from product no-  101
getting details from product no-  102
getting details from product no-  103
getting details from product no-  104
getting details from product no-  105
getting details from product no-  106
getting details from product no-  107
getting details from product no-  108
getting details from product no-  109
getting details from product no-  110
getting details from product no-  111
getting details from product no-  112
getting details from product no-  113
getting details from product no-  114
getting details from product no-  115
getting details from product no-  116
getting details from product no-  117
getting details from product no-  118
getting details from product no-  119
getting details from product no-  120
getting details from product no-  121
getting details from product no-  122
getting details from product no-  123
getting details from product no-  124
getting details from product no-  125
getting details from product no-  126
getting details from product no-  127
getting details from product no-  128
getting details from product no-  129
getting details from product no-  130
getting details from product no-  131
getting details from product no-  132
getting details from product no-  133
getting details from product no-  134
getting details from product no-  135
getting details from product no-  136
getting details from product no-  137
getting details from product no-  138
getting details from product no-  139
getting details from product no-  140
getting details from product no-  141
getting details from product no-  142
completed page no  3
-~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~-

In [440]:
#Replacing "" with "-"
for i in avail:
    if i == "":
        sr=avail.index(i)
        avail[sr]="-"
        
for i in delivery:
    if i == "":
        sr=delivery.index(i)
        delivery[sr]="-"

In [441]:
print(len(brand),len(name),len(price),len(returnable),len(delivery),len(avail),len(link))

143 143 143 143 143 143 143

In [443]:
df=pd.DataFrame({"Brand": brand, "Product name": name, "Price": price, "Return/Exchange": returnable, "Delivery": delivery, "Availability":avail, "Url":link})
df

,Brand,Product name,Price,Return/Exchange,Delivery,Availability,Url
0,[Kadence],Kadence Frontier guitar with Online Guitar lea...,"₹4,999.00",7 Days Replacement,"Sunday, 24 July",-,https://www.amazon.in/gp/slredirect/picassoRed...
1,[],Exegi Enterprise 4 String Decor Guitar Childre...,₹999,7 Days Returnable,"Monday, 25 July",In stock.,https://www.amazon.in/gp/slredirect/picassoRed...
2,[blueberry],"Blueberry B40L, 40"" Acoustic Guitar Kit Inbuil...","₹4,295",7 Days Replacement,"Wednesday, 27 July",In stock.,https://www.amazon.in/gp/slredirect/picassoRed...
3,[],Festra R-40- Trussrod Acoustic Guitar Kit with...,"₹4,295",7 Days Replacement,"Wednesday, 27 July",In stock.,https://www.amazon.in/gp/slredirect/picassoRed...
4,[JUAREZ],JUAREZ 96.52 cm (38 Inch) Acoustic Guitar with...,"₹3,169",7 Days Replacement,"Friday, 29 July",In stock.,https://www.amazon.in/JUAREZ-Acoustic-Guitar-3...
...,...,...,...,...,...,...,...
138,[],Gavison Venus Black Rosewood Fretboard Acousti...,"₹3,750",7 Days Replacement,"Friday, 29 July",In stock.,https://www.amazon.in/Gavison-Venus-Black-Rose...
139,[blueberry],"Blueberry B-G41S, 41 Inch Acoustic Guitar Kit,...","₹6,500",7 Days Replacement,"Wednesday, 27 July",Only 1 left in stock.,https://www.amazon.in/gp/slredirect/picassoRed...
140,[ActiveOwl],ActiveOwl Classical Music Instrument Plastic T...,₹299,7 Days Returnable,"Wednesday, 27 July",Only 1 left in stock.,https://www.amazon.in/gp/slredirect/picassoRed...
141,[],LME Laxmi Musical Electronics - Acoustic Picku...,₹699,7 Days Replacement,"Sunday, 24 July",In stock.,https://www.amazon.in/gp/slredirect/picassoRed...
142,[MUSTANG],Pack of 2 Universal Guitar Stand by Hola! Musi...,₹999,7 Days Replacement,"Wednesday, 27 July",Only 1 left in stock.,https://www.amazon.in/gp/slredirect/picassoRed...

In [ ]:
driver.close()

#### 3. Write a python program to access the search bar and search button on images.google.com and scrape 10 images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’, ‘Guitar’, ‘Cakes’.'''

In [1]:
import pandas as pd
import selenium 
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
import time
from selenium.webdriver.common.keys import Keys

In [2]:
driver= webdriver.Chrome(r"C:\Users\amang\chromedriver_win32\chromedriver.exe")

In [3]:
#Getting url
url= "https://images.google.com"
driver.get(url)
time.sleep(2)

In [4]:
# input in search bar
words=['fruits', 'cars', 'Machine Learning', 'Guitar', 'Cakes']
for w in words:
#input at homepage
    if w==words[0]:
        inp=driver.find_element("xpath","/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input")
        inp.send_keys(w)
        inp.send_keys(Keys.ENTER)
        time.sleep(2)
        
#input when not at home page
    else:
        inp=driver.find_element("xpath","/html/body/c-wiz/c-wiz/div/div[3]/div[2]/div/div[1]/form/div[1]/div[2]/div/div[2]/input")
        inp.send_keys(w)
        inp.send_keys(Keys.ENTER)
        time.sleep(2)
    
#getting images
    for i in range (1,11):
        s=str(i)
        frt=driver.find_element("xpath",'//*[@id="islrg"]/div[1]/div['+s+']/a[1]/div[1]/img')
        if w=='fruits':
            frt.screenshot(r'C:\Users\amang\OneDrive\Desktop\Assignment 4 img dwnld\Fruit\fruit('+str(i)+').png')
        
        elif w=='cars':
            frt.screenshot(r'C:\Users\amang\OneDrive\Desktop\Assignment 4 img dwnld\Car\car('+str(i)+').png')
    
        elif w=='Machine Learning':
            frt.screenshot(r'C:\Users\amang\OneDrive\Desktop\Assignment 4 img dwnld\ML\ML('+str(i)+').png')
        
        elif w=='Guitar':
            frt.screenshot(r'C:\Users\amang\OneDrive\Desktop\Assignment 4 img dwnld\Guitar\guitar('+str(i)+').png')
        
        elif w=='Cakes':
            frt.screenshot(r'C:\Users\amang\OneDrive\Desktop\Assignment 4 img dwnld\Cakes\cake('+str(i)+').png')
    
    time.sleep(2)
    
    for l in range (0,len(w)):
        inp=driver.find_element("xpath","/html/body/c-wiz/c-wiz/div/div[3]/div[2]/div/div[1]/form/div[1]/div[2]/div/div[2]/input")
        inp.send_keys(Keys.BACKSPACE)

In [ ]:
driver.close()

#### 4. Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on www.flipkart.com and scrape following details for all the search results displayed on 1st page. Details to be scraped: “Brand Name”, “Smartphone name”, “Colour”, “RAM”, “Storage(ROM)”, “Primary Camera”, “Secondary Camera”, “Display Size”, “Battery Capacity”, “Price”, “Product URL”. Incase if any of the details is missing then replace it by “- “. Save your results in a dataframe and CSV

In [5]:
import pandas as pd
import selenium 
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
import time
from selenium.common.exceptions import NoSuchElementException

In [6]:
driver= webdriver.Chrome(r"C:\Users\amang\chromedriver_win32\chromedriver.exe")

In [7]:
#Getting url
url= "https://www.flipkart.com"
driver.get(url)

In [8]:
#Terminate login pop up.
log=driver.find_element("xpath","/html/body/div[2]/div/div/button")
log.click()

In [18]:
# input in search bar
inp=driver.find_element("xpath","/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/div/input")
inp.send_keys("Oneplus Nord")

In [19]:
# Search
srch=driver.find_element("xpath","/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/button")
srch.click()

In [20]:
full=[]
f=driver.find_elements("xpath",'//div[@class="_4rR01T"]')
for i in f:
    full.append(i.text.split('('))
first=[]
second=[]
for i in full:
    first.append(i[0])
    second.append(i[1])
print(len(first),len(second))

24 24

In [21]:
prod=[]
brand=[]
for i in first:
#Brand name
    brand.append(i.split()[0])
    
#Product name    
    prod.append(" ".join(i.split()[1:]))   

#Colour
color=[]
for i in second:
    color.append(i.split(',')[0])

In [22]:
rm=[]
ram=[]
rom=[]
display=[]
pcamera=[]
scamera=[]
battery=[]
price=[]
link=[]

r=driver.find_elements("xpath",'//ul[@class="_1xgFaf"]')
for i in r:
    rm.append(i.text.split("\n"))

for i in rm:
#RAM
    ram.append(i[0].split('|')[0])
#ROM
    rom.append(i[0].split('|')[1])
#Display
    display.append((i[1].split(')')[0])+')')
#Primary camera
    pcamera.append(i[2].split('|')[0])
#Secondary camera    
    try:
        scamera.append(i[2].split('|')[1])
    except:
        scamera.append("-")
#battery        
    battery.append(i[3])
#price
pr=driver.find_elements("xpath",'//div[@class="_30jeq3 _1_WHN1"]')
for i in pr:
    price.append(i.text)
len(price)

#URL
l=driver.find_elements("xpath",'//a[@class="_1fQZEK"]')
for i in l:
    link.append(i.get_attribute("href"))

print(len(prod), len(brand), len(color), len(ram),len(rom),len(pcamera), len(scamera), len(battery), len(price), len(link))

24 24 24 24 24 24 24 24 24 24

In [23]:
df=pd.DataFrame({"Brand": brand, "Product":prod, 'Colour':color, 'RAM':ram, "ROM":rom, "Primary camera":pcamera, "Secondary camera":scamera, "Battery capacity":battery, "URL":link})
df

,Brand,Product,Colour,RAM,ROM,Primary camera,Secondary camera,Battery capacity,URL
0,OnePlus,Nord CE 2 Lite 5G,Blue Tide,6 GB RAM,128 GB ROM,64MP Rear Camera,16MP Front Camera,5000 mAh Battery,https://www.flipkart.com/oneplus-nord-ce-2-lit...
1,OnePlus,Nord 2T 5G,Jade Fog,12 GB RAM,256 GB ROM,50MP Rear Camera,-,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-2t-5g-ja...
2,OnePlus,Nord CE 2 5G,Gray Mirror,8 GB RAM,128 GB ROM,64MP Rear Camera,-,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-ce-2-5g-...
3,OnePlus,Nord 2 5G,Gray Sierra,8 GB RAM,128 GB ROM,50MP Rear Camera,-,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-2-5g-gra...
4,OnePlus,Nord 2T 5G,Gray Shadow,8 GB RAM,128 GB ROM,50MP Rear Camera,-,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-2t-5g-gr...
5,OnePlus,Nord CE 2 Lite 5G,Black Dusk,6 GB RAM,128 GB ROM,64MP Rear Camera,-,5000 mAh Battery,https://www.flipkart.com/oneplus-nord-ce-2-lit...
6,OnePlus,Nord CE 2 5G,Bahama Blue,8 GB RAM,128 GB ROM,64MP Rear Camera,-,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-ce-2-5g-...
7,OnePlus,Nord 2 5G,PAC-MAN,12 GB RAM,256 GB ROM,50MP Rear Camera,-,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-2-5g-pac...
8,OnePlus,Nord CE 2 Lite 5G,Black Dusk,8 GB RAM,128 GB ROM,64MP Rear Camera,-,5000 mAh Battery,https://www.flipkart.com/oneplus-nord-ce-2-lit...
9,OnePlus,Nord 2 5G,Blue Haze,8 GB RAM,128 GB ROM,50MP Rear Camera,-,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-2-5g-blu...
10,OnePlus,Nord,Gray Onyx,12 GB RAM,256 GB ROM,48MP + 8MP,32MP + 8MP Dual Front Camera,4115 mAh Battery,https://www.flipkart.com/oneplus-nord-gray-ony...
11,OnePlus,Nord,Gray Onyx,6 GB RAM,64 GB ROM,48MP + 8MP,32MP + 8MP Dual Front Camera,4115 mAh Battery,https://www.flipkart.com/oneplus-nord-gray-ony...
12,OnePlus,Nord,Blue Marble,12 GB RAM,256 GB ROM,48MP + 8MP,32MP + 8MP Dual Front Camera,4115 mAh Battery,https://www.flipkart.com/oneplus-nord-blue-mar...
13,OnePlus,Nord,Gray Onyx,8 GB RAM,128 GB ROM,48MP + 8MP,32MP + 8MP Dual Front Camera,4115 mAh Battery,https://www.flipkart.com/oneplus-nord-gray-ony...
14,OnePlus,Nord,Blue Marble,8 GB RAM,128 GB ROM,48MP + 8MP,32MP + 8MP Dual Front Camera,4115 mAh Battery,https://www.flipkart.com/oneplus-nord-blue-mar...
15,OnePlus,Nord,Blue Marble,6 GB RAM,64 GB ROM,48MP + 8MP,32MP + 8MP Dual Front Camera,4115 mAh Battery,https://www.flipkart.com/oneplus-nord-blue-mar...
16,OnePlus,Nord 2T 5G,Gray Shadow,12 GB RAM,256 GB ROM,50MP Rear Camera,-,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-2t-5g-gr...
17,OnePlus,Nord 2T 5G,Jade Fog,8 GB RAM,128 GB ROM,50MP Rear Camera,-,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-2t-5g-ja...
18,OnePlus,Nord CE 2 5G,Bahama Blue,6 GB RAM,128 GB ROM,64MP Rear Camera,-,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-ce-2-5g-...
19,OnePlus,Nord 2 5G,Gray Sierra,12 GB RAM,256 GB ROM,50MP Rear Camera,-,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-2-5g-gra...
20,OnePlus,Nord CE 2 Lite 5G,Blue Tide,8 GB RAM,128 GB ROM,64MP Rear Camera,-,5000 mAh Battery,https://www.flipkart.com/oneplus-nord-ce-2-lit...
21,OnePlus,Nord CE 5G,Blue Void,12 GB RAM,256 GB ROM,64MP Rear Camera,-,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-ce-5g-bl...
22,OnePlus,Nord CE 5G,Charcoal Ink,12 GB RAM,256 GB ROM,64MP Rear Camera,-,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-ce-5g-ch...
23,OnePlus,Nord 2 5G,Blue Haze,12 GB RAM,256 GB ROM,50MP Rear Camera,-,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-2-5g-blu...

In [25]:
df.to_csv(r'C:\Users\amang\OneDrive\Desktop\Assignment 4 img dwnld\As4_Q4.csv', index=False)

In [26]:
driver.close()

#### 5. Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on google maps.

In [42]:
import pandas as pd
import selenium 
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
import time
from selenium.webdriver.common.keys import Keys

In [43]:
driver= webdriver.Chrome(r"C:\Users\amang\chromedriver_win32\chromedriver.exe")

In [44]:
url="https://maps.google.com/"
driver.get(url)

In [45]:
city= input("Enter a name of the city to look in google maps: ")

Enter a name of the city to look in google maps: Banglore

In [46]:
inp=driver.find_element("xpath",'/html/body/div[3]/div[9]/div[3]/div[1]/div[1]/div[1]/div[2]/form/div[2]/div[3]/div/input[1]')
inp.send_keys(city)
inp.send_keys(Keys.ENTER)

In [56]:
a=(driver.current_url.split("@")[1].split(",")[:2])

In [60]:
print("Lattitude and Longitude of {2} are {0} and {1}".format(a[0], a[1], city))

Lattitude and Longitude of Banglore are 12.9538477 and 77.3507398

In [61]:
driver.close()

#### 6. Write a program to scrap details of all the funding deals for second quarter (i.e Jan 21 – March 21) from trak.in.

In [1]:
import pandas as pd
import selenium 
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
import time
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.keys import Keys

In [2]:
driver= webdriver.Chrome(r"C:\Users\amang\chromedriver_win32\chromedriver.exe")
driver.maximize_window()

In [5]:
url="https://trak.in"
driver.get(url)
time.sleep(2)

In [6]:
fund=driver.find_element("xpath",'/html/body/div[1]/header/div[2]/div/div/div/div/nav/ul/li[9]/a')
fund.click()

In [8]:
month=[]
for i in range(54,57):
    s=str(i)
    mon=driver.find_element("xpath",'//h2[@class="tablepress-table-name tablepress-table-name-id-'+str(i)+'"]')
    month.append(mon.text)
month

['January, 2021', 'February, 2021', 'March, 2021']

In [9]:
dt=driver.find_elements("xpath",'//td[@class="column-2"]')
date=[]
april=[]
for i in dt:
    z=i.text.split('/')
    if ('01' in z[1] or'02' in z[1] or'03' in z[1]) and('2021') in z[2]:
        date.append(i.text)
    elif '04' in z[1] and('2021') in z[2]:
        april.append(i.text)
    else:
        break
len(date)

24

In [104]:
sr=[]
st_name=[]
industry=[]
s_vertical=[]
city=[]
investor=[]
investment=[]
amount=[]

In [105]:
for j in range(1,10):
    if j==2:
        continue
    sv=driver.find_elements("xpath",'//td[@class="column-'+str(j)+'"]')
    c=0
    for i in sv:
        if c<len(april):
            c+=1
            continue
            
        if j==1:
            if len(sr)==len(date):
                break
            sr.append(i.text)
        
        
        if j==3:
            if len(st_name)==len(date):
                break
            st_name.append(i.text)
            
        if j==4:
            if len(industry)==len(date):
                break
            industry.append(i.text)
            
        if j==5:
            if len(s_vertical)==len(date):
                break
            s_vertical.append(i.text)
        
        if j==6:
            if len(city)==len(date):
                break
            city.append(i.text)
            
        if j==7:
            if len(investor)==len(date):
                break
            investor.append(i.text)
            
        if j==8:
            if len(investment)==len(date):
                break
            investment.append(i.text)
        
        if j==9:
            if len(amount)==len(date):
                break
            amount.append(i.text)  
            
            
            
print(len(sr),len(date),len(st_name),len(industry),len(s_vertical),len(city),len(investor),len(investment),len(amount))

24 24 24 24 24 24 24 24 24

In [124]:
df=pd.DataFrame({"Date": date, "Startup name": st_name, "Industry":industry, "Sub-vertical":s_vertical, "City":city, "Investors' name": investor, "Investment type":investment, 'Amount in USD':amount})
#reverse columns of DF
df=df.iloc[::-1]
df["Sr. no."]= sr
df.set_index("Sr. no.")

,Date,Startup name,Industry,Sub-vertical,City,Investors' name,Investment type,Amount in USD
Sr. no.,,,,,,,,
1,13/01/2021,Saveo,B2B E-commerce,Pharmacies,Bengaluru,"Matrix Partners India, RTP Global, others",Seed,"4,000,000"
2,11/01/2021,True Elements,Food Startup,Whole Food plant based Nashta,Pune,SIDBI Venture Capital,Series,"100,000,000"
3,18/01/2021,Udayy,EdTech,Online learning platform for kids in class 1-5,Gurgaon,Sequoia Capital,Seed Funding,"15,000,000"
4,18/01/2021,mfine,Health Tech Startup,AI-powered telemedicine mobile app,Bengaluru,Heritas Capital Management,Venture Round,"16,000,000"
5,19/01/2021,Darwinbox,SaaS,HR Tech,Mumbai,Salesforce Ventures,Seed,"15,000,000"
6,19/01/2021,DeHaat,AgriTech Startup,online marketplace for farm products and services,Patna,Prosus Ventures,Series C,"30,000,000"
7,28/01/2021,Bombay Shaving Company,Consumer Goods Company,"Shave care, beard care, and skincare products",New Delhi,Reckitt Benckiser,Venture,"6,172,258.50"
1,15/01/2021,Digit Insurance,Financial Services,Insurance Services,Bengaluru,"A91 Partners, Faering Capital, TVS Capital Funds",Venture,"1,80,00,000"
2,09/02/2021,SplashLearn,EdTech,Game-based learning programme,Gurgaon,Owl Ventures,Series C,"18,000,000"
3,09/02/2021,Nothing,Technology,Consumer Technology Venture,London,GV,Series A,"15,000,000"
4,12/02/2021,Grofers,E-Commerce,Online supermarket,Gurgaon,SoftBank Vision Fund (SVF),Unspecified,"55,000,000"
5,12/02/2021,Pepperfry,E-commerce,Multi-brand furniture brand,Mumbai,InnoVen Capital,Debt Financing,"4,773,958"
6,15/02/2021,KreditBee,Finance,Digital lending platform,Bengaluru,Azim Premji’s PremjiInvest and South Korea’s M...,Series C,"75,000,000"
7,17/02/2021,Zolve,FinTech,Global Neobank Venture,Mumbai,Accel Partners and Lightspeed Venture Partners,Seed,"1,50,00,000"
8,19/02/2021,Fingerlix,Hospitality,Semi-cooked food delivery app,Mumbai,"Rhodium Trust, Accel Partners and Swiggy",Series C,"2,747,045.20"
9,22/02/2021,Zomato,Hospitality,Online Food Delivery Platform,Gurgaon,"Tiger Global, Kora",Venture,"250,000,000"
1,11/02/2021,Doubtnut,Edu Tech,E-Learning Platform,Gurgaon,"SIG Global, Sequoia Capital, WaterBridge Ventu...",Series B,"2,500,000"
2,26/03/2021,DotPe,FinTech,Commerce and payments platform to offline ente...,Gurgaon,PayU,Series A,"27,500,000"
3,25/03/2021,CityMall,E-commerce,Social ecommerce and online grocery platform,Gurgaon,Accel Partners,Series A,"11,000,000"
4,23/03/2021,SkilloVilla,Edu-tech,Career and job-oriented upskilling.,Bengaluru,"Titan Capital, others",Seed,"300,000,000"
5,30/03/2021,BYJU’S,Edu-tech,Online tutoring,Bengaluru,"MC Global Edtech, B Capital, Baron, others",Series F,"460,000,000"
6,30/03/2021,Dunzo,E-commerce,Hyper-local delivery app,Bengaluru,Krishtal Advisors Pte Ltd,Series E,"8,000,000"
7,31/03/2021,Uniphore,Technology,Conversational Service Automation (CSA),Palo Alto,Sorenson Capital Partners,Series D,"140,000,000"
8,04/03/2021,DealShare,E-commerce,Online shopping platform,"Jaipur, Rajasthan",Innoven Capital,Debt Financing,"250,000,000"

In [126]:
driver.close()

#### 7. Write a program to scrap all the available details of best gaming laptops from digit.in.

In [241]:
import pandas as pd
import selenium 
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
import time

In [242]:
driver= webdriver.Chrome(r"C:\Users\amang\chromedriver_win32\chromedriver.exe")
driver.maximize_window()

In [243]:
url="https://www.digit.in/"
driver.get(url)
time.sleep(2)

In [244]:
top=driver.find_element("xpath","/html/body/div[1]/div/div[4]/ul/li[4]/a")
top.click()

In [245]:
for i in range (1,50):
    bst=driver.find_element("xpath","/html/body/div[3]/div/div/div[3]/div[2]/ul/li["+str(i)+"]/a")
    if bst.text == "Best Gaming Laptops in India":
        bst.click()
        time.sleep(2)
        break

In [246]:
product=[]
seller=[]
price=[]
for j in range (1,11):
    for i in range (1,4):
        pr=driver.find_element("xpath",'//*[@id="summtable"]/tbody/tr['+str(j)+']/td['+str(i)+']')
        if i==1:
            product.append(pr.text)
        if i==2:
            seller.append(pr.text)
        if i==3:
            price.append(pr.text)

print(len(product), len(seller), len(price))

10 10 10

In [247]:
df=pd.DataFrame({"Product": product, "Seller": seller, "Price": price})
df

                                         Product  Seller      Price
0                           MSI Titan GT77-12UHS     N/A        N/A
1                               Alienware x17 R2    Dell  ₹ 389,990
2          Acer Predator Triton 500 SE PT516-52s     N/A  ₹ 300,000
3                        Omen by HP (16-B1371TX)  Amazon  ₹ 170,990
4  Acer Predator Helios 300 AN515-45 (NH.QBRSI.0     N/A  ₹ 172,999
5                     MSI Delta 15 (A5EFK-083IN)     N/A  ₹ 188,990
6                        Omen by HP (16-c0141AX)  Amazon  ₹ 129,899
7              Lenovo Legion 5i Pro (82RF00MGIN)     N/A  ₹ 230,890
8  Alienware m15 R5 Ryzen Edition icc-c780001win    Dell  ₹ 144,990
9               Lenovo Slim 7 Gen 6 (82K8002JIN)   Croma  ₹ 142,990

In [262]:
#get product names class="TopNumbeHeading sticky-footer active"
name=[]
nm=driver.find_elements("xpath",'//div[@class="TopNumbeHeading sticky-footer" or @class="TopNumbeHeading sticky-footer active"]')
for i in nm:
    name.append(" ".join(i.text.split('\n')))

In [264]:
#Get specs of the product
specs=[]
sp=driver.find_elements("xpath",'//div[@class="Specs-Wrap"]')
for i in sp:
    specs.append(i.text.split('\n'))

In [266]:
#get description
desc=[]
ds=driver.find_elements("xpath",'//div[@class="Section-center"]')
for i in ds:
    desc.append(i.text.split('\n')[:][0:8])

In [268]:
print(len(name),len(specs),len(desc))

10 10 10

In [270]:
for i in range(0,len(product)):
    print(name[i])
    print("Specifications are \n {0}".format(specs[i]))
    print("Details are \n {0}\n".format(desc[i]))

1. MSI TITAN GT77-12UHS
Specifications are
 ['WINDOWS 11 HOME OS', '17.3" (3840 X 2160) DISPLAY', '12TH GEN INTEL CORE I9-12900HX | NA PROCESSOR', '2 TB SSD/64 GB DDR5 MEMORY']
Details are
 ['The very best MSI gaming laptop featuring an Intel processor is the MSI TITAN GT77 - 12UHS. This is the top of the line model from MSI’s recent refresh of their entire gaming lineup and is powered by the Intel Core i9-12900HX which is a 16 Core (8P+8E) processor that has 24 threads and a maximum Turbo power of 157 Watts. The graphics card in this laptop is the NVIDIA RTX 3080 Ti and it too sports a high TGP of 175 Watts. This is one of the most powerful CPU+GPU combinations with plenty of thermal headroom to allow it to operate at higher clock speeds for longer time periods. As for the memory, the MSI GT77-12UHS can have up to 128 GB of DDR5 memory but ships with 64 GB DDR5 clocked at 4800 MT/s. Being a 12th Gen machine also means that the motherboard has PCIe Gen 5.0 lanes for storage devices such as M.2 SSDs. The GT77-12UHS has four M.2 slots of which one slot is PCIe Gen 5 whereas the remaining three are PCIe Gen 4 slots. Then there’s also the display, the GT77-12UHS features a massive 17.3-inch IPS-level 4K panel with a 120 Hz refresh rate. So you can actually enjoy all the high frame-rate gameplay that the powerful hardware enables. And the cherry on the cake? A built-in mechanical keyboard with Cherry MX switches. All this hardware comes at a ridiculous price of INR 5,26,990. As of now, this is at the top among the best performing gaming laptops in the world.', 'SPECIFICATION', 'Processor : 12th Gen Intel Core i9-12900HX 16 core processor', 'Display : 17.3″ (3840 x 2160) screen, 120 Hz refresh rate', 'OS : Windows 11 Home', 'Memory : 64 GB DDR5 RAM & 2 TB SSD', 'Graphics Processor : 16 GB DDR6 NVIDIA GeForce RTX 3080 Ti Graphics card', 'Body : 397 x 330 x 23 mm dimension & 3.3 kg weight']

2. ALIENWARE X17 R2
Specifications are
 ['WINDOWS 11 HOME OS', '17.3" (1920X1080) DISPLAY', '12TH GEN INTEL CORE I9-12900HK | 5.00 GHZ PROCESSOR', '1 TB SSD/32 GB DDR5 MEMORY']
Details are
 ['Alienware, the premium gaming brand from Dell has its own reputation for building some of the meanest gaming machines for more than two decades. The best Alienware gaming laptop featuring an Intel processor is the Alienware x17 R2. This thing packs an Intel Core i9-12900HK which is a 14-Core (6P+8E) processor which has 20 Threads. The lower P-Core count helps it hit slightly higher clock speeds but the Max Turbo power is capped at 115W which is less than what the MSI GT77 sports. As for the graphics card, the Alienware x17 R2 also sports an NVIDIA RTX 3080 Ti with the peak TGP set to 175 Watts. The CPU+GPU combination of the Alienware x17 R2 comes close to the MSI GT77. As for the memory, the Alienware x17 R2 ships with 32 GB of DDR5 RAM clocked at 4800 MT/s. The display on the x17 R2 is a 17.3-inch FHD 360 Hz panel compared to the 120 Hz 4K panel on the MSI GT77. You’ll end up seeing higher frame rates on the Alienware x17 R2 without any tearing whereas you’ll see crisper visuals at high frame rates on the MSI GT77. Both make for great experiences. This configuration of the Dell Alienware x17 R2 goes for INR 3,89,990 making it a good gaming laptop to buy in 2022.', 'SPECIFICATION', 'Processor : 12th Gen Intel Core i9-12900HK 14 core processor with 5.00 GHz clock speed', 'Display : 17.3″ (1920x1080) screen, 360 Hz refresh rate', 'OS : Windows 11 Home', 'Memory : 32 GB DDR5 RAM & 1 TB SSD', 'Graphics Processor : 16 GB DDR6 NVIDIA GeForce RTX 3080 Ti, Graphics card', 'Body : 399.23 x 299.57 x 14.75 mm dimension & 3.02 kg weight']

3. ACER PREDATOR TRITON 500 SE PT516-52S
Specifications are
 ['WINDOWS 11 HOME OS', '16" (2560 X 1600) DISPLAY', '12TH GEN INTEL CORE I7-12700H | 3.50 GHZ PROCESSOR', '2 TB SSD/32 GB DDR5 MEMORY']
Details are
 ['The Predator lineup from Acer has shown great promise for gamers ever since they showcased the Predator 21X a couple of years ago. Keeping its legacy intact and also being the best Acer gaming laptop featuring an Intel processor is the Acer Predator Triton 500 SE. This machine is powered by an Intel Core i7-12700H which is a 14-Core (6P+8E) processor with 20 Threads. And the graphics card in this machine is the NVIDIA RTX 3070 Ti. The TGP isn’t specified but the RTX 3070 Ti generally ships with a TGP of between 105 to 150 Watts. For the memory, it has 32 GB of LPDDR5 memory clocked at 4800 MT/s and the display is a 16-inch 2560x1600 IPS panel sporting a 240 Hz refresh rate. Acer makes some intelligent decisions with the hardware by picking a Core i7 processor and pairing it with a high-end RTX 3070 Ti. The power backup in this machine is a 4-Cell 99 Wh Li-ion battery which is the highest that you can get in a laptop legally for it to be carried on aeroplanes. And if we are to talk about the networking then the Acer Predator Triton 500 SE comes with Killer Wi-Fi 6E 1675s and Gigabit Ethernet. This laptop gives you great gaming performance that comes close to machines that cost twice as much. Speaking of price, the Acer Predator Triton 500 SE PT516-52s is priced at INR 2,29,999 in India.', 'SPECIFICATION', 'Processor : 12th Gen Intel Core i7-12700H 14 core processor with 3.50 GHz clock speed', 'Display : 16″ (2560 x 1600) screen, 240 Hz refresh rate', 'OS : Windows 11 Home', 'Memory : 32 GB DDR5 RAM & 2 TB SSD', 'Graphics Processor : 8 GB DDR6 NVIDIA GeForce RTXTM 3070 Ti Graphics card', 'Body : 358 x 262 x 19.9 mm dimension & 2.4 kg weight']

4. OMEN BY HP (16-B1371TX)
Specifications are
 ['WINDOWS 11 HOME OS', '16.1" (2560 X 1440) DISPLAY', '12TH GEN INTEL CORE I7-12700H | 4.7 GHZ PROCESSOR', '1 TB SSD/8 GB DDR5 MEMORY']
Details are
 ['Omen by HP is a premium gaming lineup which is right up there with their Victus gaming laptops. The best HP gaming laptop with an Intel processor is the Omen by HP (16-B1371TX). Like the Acer Predator, this too is powered by the Intel Core i7-12700H which is a 14-Core (6P+8E) processor with 20 Threads. And the graphics card in this machine is the NVIDIA RTX 3070 Ti. Even the memory is a similar configuration with 32 GB of DDR5 RAM rated for 4800 MT/s. One of the great things about the Omen laptops is that the audio setup is powered by Bang&Olufsen for some really great-sounding audio. For the display, the Omen by HP (16-B1371TX) sports a 16.1-inch 165 Hz 2560x1440 IPS panel that is the best of both worlds, resolution and refresh rate. Moreover, it is also NVIDIA G-Sync certified. The keyboard on the HP Omen (16-B1371TX) features a 4-zone RGB backlighting that adds a bit of pizazz to the overall aesthetic. In a way, the HP Omen (16-B1371TX) checks all the boxes and it does so with a price tag of INR 1,82,999 in India.', 'SPECIFICATION', 'Processor : 12th Gen Intel Core i7-12700H 14 core processor with 4.7 GHz clock speed', 'Display : 16.1″ (2560 x 1440) screen', 'OS : Windows 11 Home', 'Memory : 8 GB DDR5 RAM & 1 TB SSD', 'Graphics Processor : 8 GB GDDR6 NVIDIA GeForce RTX 3070 Graphics card', 'Body : 369 x 248 x 23 mm dimension & 2.32 kg weight']

5. ACER PREDATOR HELIOS 300 AN515-45 (NH.QBRSI.0
Specifications are
 ['WINDOWS 11 HOME OS', '15.6" (2560 X 1440) DISPLAY', 'AMD RYZEN 9-5900HX | NA PROCESSOR', '512 GB SSD/16 GB DDR4 MEMORY']
Details are
 ['Acer Predator Helios 300 AN515-45 is the best Acer gaming laptop featuring an AMD processor. It is powered by the AMD Ryzen 9 5900HX which is an 8 Core processor that gives you 16 Threads. AMD’s Ryzen 5000 series processors have broken performance records and set new benchmarks and this is the best mobile processor of the entire series. Acer has paired this with the NVIDIA RTX 3070. Together, the two make for a great combination for gaming. On the memory front, there’s 16 GB of DDR4 RAM clocked at 3200 MT/s. The display on the Acer Predator Helios 300 is a 15.6-inch 2560x1440 IPS panel that is tuned for a refresh rate of 165 Hz. Acer also packs Killer E2600 Ethernet in the Predator Helios 300 for folks who’d like to tweak their network prioritisation settings. The TGP for the RTX 3070 has not been mentioned here but a high TGP RTX 3070 can even best a low TGP RTX 3070 Ti, so there might be a few surprises there. For all these features, the Acer Predator Helios 300 carries a price tag of INR 1,39,990 in India.', 'SPECIFICATION', 'Processor : AMD Ryzen 9-5900HX 8 core processor', 'Display : 15.6″ (2560 x 1440) screen, 165 Hz refresh rate', 'OS : Windows 11 Home', 'Memory : 16 GB DDR4 RAM & 512 GB SSD', 'Graphics Processor : 8 GB DDR6 NVIDIA GeForce RTX 3070 Graphics card', 'Body : 363 x 255 x 23.9 mm dimension & 2.4 kg weight']

6. MSI DELTA 15 (A5EFK-083IN)
Specifications are
 ['WINDOWS 11 HOME OS', '15.6" (1920 X 1080) DISPLAY', 'AMD 5TH GEN RYZEN 9-5900HX | 3.3GHZ PROCESSOR', '1 TB SSD/16 GB DDR4 MEMORY']
Details are
 ["The best MSI gaming laptop with an AMD processor is the MSI Delta 15 A5EFK-083IN. It features the top of the line AMD Ryzen 9 5900 HX which is a great 8-Core / 16-Thread processor for gaming and for the graphics card it has an AMD Radeon RX 6700M. The Radeon RX 6000 series graphics cards are well known for their power efficiency thanks to the efficient 7nm process on which the Radeon RX 6000 GPUs are built on. The RX 6700M, in particular, is a great high-end graphics card and can best even an RTX 3070 considering the TGP ranges of the GPUs. For the memory, the MSI Delta 15 comes with 16 GB of dual-channel DDR4 RAM clocked at 3200 MT/s. Coming to the display, the MSI Delta 15 sports a 15.6-inch FHD IPS-level 240 Hz panel that's geared to take advantage of AMD FreeSync. Even the backup is great with an 82 Wh 4-Cell Li-Ion battery. The keyboard on the Delta 15 is backlit and there's always the MSI Dragon Centre management software to help optimise the way you use the laptop. The MSI Delta 15 A5EFK-083IN retails for INR 1,14,990 in India.", 'SPECIFICATION', 'Processor : AMD 5th Gen Ryzen 9-5900HX 8 core processor with 3.3GHz clock speed', 'Display : 15.6″ (1920 x 1080) screen, 240Hz refresh rate', 'OS : Windows 11 Home', 'Memory : 16 GB DDR4 RAM & 1 TB SSD', 'Graphics Processor : 10 GB DDR6 AMD Radeon RX 6700M Graphics card', 'Body : 357 x 247 x 19 mm dimension & 1.9 kg weight']

7. OMEN BY HP (16-C0141AX)
Specifications are
 ['WINDOWS 11 HOME OS', '16.1" (2560 X 1440) DISPLAY', 'AMD RYZEN™ 9 5900HX | 3.3 GHZ PROCESSOR', '1 TB NVME/16 GB DDR4 MEMORY']
Details are
 ["Another worthy gaming laptop from the Omen lineup from HP is the 16-c0141AX. In fact, it's also the best HP gaming laptop with an AMD Processor. This unit also features the best AMD mobile processor which is the AMD Ryzen 9 5900 HX, an 8-Core / 16-Thread flagship CPU that can make mincemeat of all current AAA video games. And for the graphics, HP has included the AMD Radeon RX 6600M which is very power efficient like most GPUs in the RX 6000 series and often performs better than the NVIDIA RTX 3060. Aside from these there’s 16 GB of DDR4 RAM, and for the display, the Omen by HP (16-c0141AX) has a 16.1-inch 2560x1440 IPS panel and it even has a high refresh rate of 165 Hz. HP introduced the OMEN Tempest Cooling technology for their laptops to improve their cooling. Like other Omen laptops, this model also has an audio solution powered by Bang&Olufsen which is a well-known premium audio brand. The Omen by HP (16-c0141AX) retails for INR 1,34,999 in India.", 'SPECIFICATION', 'Processor : AMD Ryzen™ 9 5900HX 8 core processor with 3.3 GHz clock speed', 'Display : 16.1″ (2560 x 1440) screen', 'OS : Windows 11 Home', 'Memory : 16 GB DDR4 RAM & 1 TB NVMe', 'Graphics Processor : 8 GB GDDR6 AMD Radeon™ RX 6600M Graphics card', 'Body : 36.92 x 24.8 x 2.3 mm dimension & 2.3 kg weight']

8. LENOVO LEGION 5I PRO (82RF00MGIN)
Specifications are
 ['WINDOWS 11 HOME OS', '16" (2560 X 1600) DISPLAY', '12TH GEN INTEL CORE I7-12700H | 3.50 GHZ PROCESSOR', '1 TB SSD/16 GB DDR5 MEMORY']
Details are
 ['Lenovo has gone a little mainstream with their gaming laptops and the best Lenovo gaming laptop featuring an Intel processor happens to be the Lenovo Legion 5i Pro (82RF00MGIN). It features the powerful Intel Core i7-12700H which is a 14-Core (6P+8E) processor with 20 Threads. There’s 16 GB of DDR5 RAM rated for 4800 MT/s and the graphics card is the NVIDIA RTX 3060. There’s no mention of the TGP of the card on the official spec sheets. Lenovo offers a 16-inch 2560x1600 IPS panel on the Lenovo Legion 5i Pro and it also has a refresh rate of 165 Hz. While most of the specs might seem a little tame compared to the top laptop on this page, the battery is where Lenovo doesn’t hold back any punches. This machine features an 80 Wh 4-Cell battery which is pretty high among gaming laptops. Then there’s the audio setup which is enhanced by Nahimic’s AI-based audio solution for different sound profiles and some of the features can improve your gaming experience. The Lenovo Legion 5i Pro (82RF00MGIN) is priced at INR 1,64,990 in India.', 'SPECIFICATION', 'Processor : 12th Gen Intel Core i7-12700H 14 core processor with 3.50 GHz clock speed', 'Display : 16″ (2560 x 1600) screen, 165 Hz refresh rate', 'OS : Windows 11 Home', 'Memory : 16 GB DDR5 RAM & 1 TB SSD', 'Graphics Processor : 6 GB DDR6 NVIDIA GeForce RTX 3060 Graphics card', 'Body : 359.9 x 264.4 x 19.9 mm dimension & 2.5 kg weight']

9. ALIENWARE M15 R5 RYZEN EDITION ICC-C780001WIN
Specifications are
 ['WINDOWS 11 HOME OS', '15.6" (1920 X 1080) DISPLAY', 'AMD RYZEN R7-5800H | 4.40 GHZ PROCESSOR', '512 GB SSD/16 GB DDR4 MEMORY']
Details are
 ['Dell not only has gaming laptops under the Dell Gaming brand but also under the Alienware brand. Together, both of them make up for a diverse set of configurations featuring the best hardware that money can buy. If you’re looking for the best Alienware gaming laptop with an AMD processor then the aptly named Alienware m15 R5 Ryzen Edition should be first on your list. This machine features the AMD Ryzen 7 5800H which is an 8-Core / 16-Thread CPU and for the graphics bit, it has an NVIDIA RTX 3060. Being an Alienware machine, you can safely assume that the TGP on the RTX 3060 will be scaled to its maximum allowed limits. As for the networking bit, the Alienware m15 R5 Ryzen Edition comes with Killer Wireless Wi-Fi 6E (1650) which is a top-tier Wi-Fi card that allows you to prioritise networking traffic so that your online gaming experience remains unhampered. As for the display, the Alienware m15 R5 Ryzen Edition comes with a 15.6-inch FHD panel tweaked for a refresh rate of 165 Hz. The Alienware m15 R5 Ryzen Edition retails for INR 1,44,989 in India.', 'SPECIFICATION', 'Processor : AMD Ryzen R7-5800H 8 core processor with 4.40 GHz clock speed', 'Display : 15.6″ (1920 x 1080) screen, 165Hz refresh rate', 'OS : Windows 11 Home', 'Memory : 16 GB DDR4 RAM & 512 GB SSD', 'Graphics Processor : 6 GB DDR6 NVIDIA GeForce RTX 3060 Graphics card', 'Body : 356.2 x 272.5 x 22.85 mm dimension & 2.69 kg weight']

10. LENOVO SLIM 7 GEN 6 (82K8002JIN)
Specifications are
 ['WINDOWS 11 HOME OS', '15.6 MP | NA DISPLAY', 'LENOVO RYZEN 7-5800H | 3.2 GHZ PROCESSOR', '1 TB SSD/16 GB DDR4 MEMORY']
Details are
 ['Lenovo has been pushing for thinner gaming laptops and the fruits of their labour can be clearly seen in the Lenovo Slim 7 Gen 6 gaming laptop. It is the best Lenovo gaming laptop featuring AMD hardware. For the processor it has an AMD Ryzen 7 5800H which is an 8-Core / 16-Thread CPU similar to the Ryzen 9 5900HX but with a lower TDP cap and slightly lower clock speeds. Nevertheless, for gaming, it’s a great processor. The Ryzen 7 5800H is clubbed with the NVIDIA RTX 3060 and there’s even 16 GB of DDR4 RAM clocked at 3200 MT/s. Like the other Lenovo machine in this list, even the Lenovo Slim 7 Gen 6 comes with a 15.6-inch 2560x1440 IPS panel sporting a 165 Hz refresh rate. And it is also certified to work with NVIDIA G-Sync technology. The thin chassis of the Lenovo Slim 7 Gen 6 is made with a combination of aluminium and magnesium for a solid finish and the chassis also doubles up as a passive heat sink. For the power backup, the Lenovo Slim 7 Gen 6 features a 71 Wh 4-Cell Lithium Ion battery. Gamers can find the Lenovo Slim 7 Gen 6 retailing for INR 1,44,990 in India.', 'SPECIFICATION', 'Processor : Lenovo Ryzen 7-5800H processor with 3.2 GHz clock speed', 'Display : 15.6″ screen, 165 Hz refresh rate', 'OS : Windows 11 Home', 'Memory : 16 GB DDR4 RAM & 1 TB SSD', 'Graphics Processor : 6 GB DDR6 NVIDIA GeForce 3060 Max-Q Graphics card', 'Body : 356 x 252 x 16 mm dimension & 1.9 kg weight']

In [271]:
driver.close()

#### 8. Write a python program to scrape the details for all billionaires from www.forbes.com. Details to be scrapped: “Rank”, “Name”, “Net worth”, “Age”, “Citizenship”, “Source”, “Industry”.

In [362]:
import pandas as pd
import selenium 
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
import time
from selenium.common.exceptions import ElementClickInterceptedException

In [420]:
driver= webdriver.Chrome(r"C:\Users\amang\chromedriver_win32\chromedriver.exe")
driver.maximize_window()

In [433]:
#Getting url
url= "http://www.forbes.com/"
driver.get(url)
time.sleep(2)

In [434]:
bil=driver.find_element("xpath",'/html/body/div[1]/main/section[8]/div[1]')
bil.click()
time.sleep(5)

In [435]:
lst=driver.find_element("xpath",'/html/body/div[1]/main/div/section/section[1]/div/div/div[1]/div/div[1]/div[1]/div[2]')
lst.click()
time.sleep(15)

In [440]:
rank=[]
name=[]
worth=[]
age=[]
country=[]
source=[]
industry=[]

In [441]:
print("Getting Started.....")
while True:
    rnk= driver.find_elements('xpath','//div[@class="table-row expanded" or @class="table-row "]')
    
#Gets each and everything from table
    aio=[] #all in one
    for i in rnk:
        aio.append(i.text.split('\n'))
        
#Gets each element
    for i in aio:
        c=0
        rank.append(i[c])
        c+=1
        name.append(i[c])
        c+=1
        worth.append(i[c])
        c+=1
        age.append(i[c])
        c+=1
        country.append(i[c])
        c+=1
        source.append(i[c])
        c+=1
        industry.append(i[c])
    print("This page scrapping completed and now the lengths of each elements are: ")
    print(len(rank),len(name),len(worth),len(age),len(country),len(source),len(industry))
    print("-x-"*20)
    time.sleep(5)
    
#next button
    nxt=driver.find_element('xpath','//div[@class="next-page"]')
    
    #print(nxt.text[5:])
    try:
        nxt.click()
        print("Moving to next page...")
        time.sleep(3)
    except ElementClickInterceptedException:
        break
        
print("Scrapping of all pages Completed")

Getting Started.....
This page scrapping completed and now the lengths of each elements are:
200 200 200 200 200 200 200
-x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x-
Moving to next page...
This page scrapping completed and now the lengths of each elements are:
400 400 400 400 400 400 400
-x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x-
Moving to next page...
This page scrapping completed and now the lengths of each elements are:
600 600 600 600 600 600 600
-x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x-
Moving to next page...
This page scrapping completed and now the lengths of each elements are:
800 800 800 800 800 800 800
-x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x-
Moving to next page...
This page scrapping completed and now the lengths of each elements are:
1000 1000 1000 1000 1000 1000 1000
-x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x-
Moving to next page...
This page scrapping completed and now the lengths of each elements are:
1200 1200 1200 1200 1200 1200 1200
-x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x-
Moving to next page...
This page scrapping completed and now the lengths of each elements are:
1400 1400 1400 1400 1400 1400 1400
-x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x-
Moving to next page...
This page scrapping completed and now the lengths of each elements are:
1600 1600 1600 1600 1600 1600 1600
-x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x-
Moving to next page...
This page scrapping completed and now the lengths of each elements are:
1800 1800 1800 1800 1800 1800 1800
-x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x-
Moving to next page...
This page scrapping completed and now the lengths of each elements are:
2000 2000 2000 2000 2000 2000 2000
-x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x-
Moving to next page...
This page scrapping completed and now the lengths of each elements are:
2200 2200 2200 2200 2200 2200 2200
-x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x-
Moving to next page...
This page scrapping completed and now the lengths of each elements are:
2400 2400 2400 2400 2400 2400 2400
-x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x-
Moving to next page...
This page scrapping completed and now the lengths of each elements are:
2600 2600 2600 2600 2600 2600 2600
-x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x-
Moving to next page...
This page scrapping completed and now the lengths of each elements are:
2668 2668 2668 2668 2668 2668 2668
-x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x-
Scrapping of all pages Completed

In [442]:
print(len(rank),len(name),len(worth),len(age),len(country),len(source),len(industry))

2668 2668 2668 2668 2668 2668 2668

In [443]:
df=pd.DataFrame({"Rank":rank, "Name": name, 'Net worth': worth, "Age":age, "Citizenship":country, "Industry":industry})
df.set_index("Rank")

,Name,Net worth,Age,Citizenship,Industry
Rank,,,,,
1.,Elon Musk,$219 B,50,United States,Automotive
2.,Jeff Bezos,$171 B,58,United States,Technology
3.,Bernard Arnault & family,$158 B,73,France,Fashion & Retail
4.,Bill Gates,$129 B,66,United States,Technology
5.,Warren Buffett,$118 B,91,United States,Finance & Investments
...,...,...,...,...,...
2578.,Zhang Yuqiang,$1 B,66,China,Manufacturing
2578.,Zhou Ruxin,$1 B,59,China,Technology
2578.,Wen Zhou & family,$1 B,57,China,Manufacturing
2578.,Zhou Yifeng & family,$1 B,43,China,Energy
2578.,Zhuang Kuilong & family,$1 B,59,China,Manufacturing

In [444]:
driver.close()

#### 9. Write a program to extract at least 500 Comments, Comment upvote and time when comment was posted from any YouTube Video.

In [698]:
import pandas as pd
import selenium 
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
import time
from selenium.webdriver.common.keys import Keys

In [699]:
driver= webdriver.Chrome(r"C:\Users\amang\chromedriver_win32\chromedriver.exe")
driver.maximize_window()

In [700]:
#Getting url
url= "https://www.youtube.com"
driver.get(url)
time.sleep(2)

In [701]:
# input in search bar
inp=driver.find_element("xpath","/html/body/ytd-app/div[1]/div/ytd-masthead/div[3]/div[2]/ytd-searchbox/form/div[1]/div[1]/input")
inp.send_keys("top 10 best upcoming smartphones")
inp.send_keys(Keys.ENTER)
time.sleep(2)

In [702]:
#open video
vd=driver.find_element("xpath",'/html/body/ytd-app/div[1]/ytd-page-manager/ytd-search/div[1]/ytd-two-column-search-results-renderer/div/ytd-section-list-renderer/div[2]/ytd-item-section-renderer/div[3]/ytd-video-renderer[1]/div[1]/div/div[1]/div/h3/a')
vd.click()
time.sleep(15)

In [703]:
comment=[]
upvote=[]
times=[]

In [704]:

    '''if len(times)>=500:
        print("breaking loop")
        break'''

'''#loading comments
    cmnt=driver.find_elements("xpath",'//yt-formatted-string[@class="style-scope ytd-comment-renderer"]')
    for i in cmnt:
        comment.append(i.text)

#upvotes
    upvt=driver.find_elements("xpath",'//ytd-comment-action-buttons-renderer[@class="style-scope ytd-comment-renderer"]')
    #print(upvt.text.split("\n")[0])
    for i in upvt:
        if(len(i.text.split("\n")))!=2:
            upvote.append("0")
        else:
            upvote.append(i.text.split("\n")[0])
            
#Timestamp
    tme=driver.find_elements("xpath",'//yt-formatted-string[@class="published-time-text style-scope ytd-comment-renderer"]')
    for i in tme:
        times.append(i.text)
    print("Now length of each elements are: ")    
    print(len(comment),len(upvote),len(times))
    
    
print(len(comment),len(upvote),len(times))'''

'#loading comments\ncmnt=driver.find_elements("xpath",\'//yt-formatted-string[@class="style-scope ytd-comment-renderer"]\')\nfor i in cmnt:\n    comment.append(i.text)\n\n#upvotes\nupvt=driver.find_elements("xpath",\'//ytd-comment-action-buttons-renderer[@class="style-scope ytd-comment-renderer"]\')\n#print(upvt.text.split("\n")[0])\nfor i in upvt:\n    if(len(i.text.split("\n")))!=2:\n        upvote.append("0")\n    else:\n        upvote.append(i.text.split("\n")[0])\n        \n#Timestamp\ntme=driver.find_elements("xpath",\'//yt-formatted-string[@class="published-time-text style-scope ytd-comment-renderer"]\')\nfor i in tme:\n    times.append(i.text)\nprint("Now length of each elements are: ")    \nprint(len(comment),len(upvote),len(times))\n\n\nprint(len(comment),len(upvote),len(times))'

In [705]:
#Scroll through all the comments to load them
c=0
while c<=65000:
    c+=500
    driver.execute_script("window.scrollTo(0,"+str(c)+");")
    time.sleep(5)
    
    
#Comments
cmnt=driver.find_elements("xpath",'//yt-formatted-string[@class="style-scope ytd-comment-renderer"]')
for i in cmnt:
    if len(comment)>=500:
        break
    comment.append(i.text)
print(len(comment))

#upvotes
upvt=driver.find_elements("xpath",'//ytd-comment-action-buttons-renderer[@class="style-scope ytd-comment-renderer"]')
#print(upvt.text.split("\n")[0])
for i in upvt:
    if len(upvote)>=500:
        break
    if(len(i.text.split("\n")))!=2:
        upvote.append("0")
    else:
        upvote.append(i.text.split("\n")[0])
print(len(upvote))

#time stamp
tme=driver.find_elements("xpath",'//yt-formatted-string[@class="published-time-text style-scope ytd-comment-renderer"]')
for i in tme:
    if len(times)>=500:
        break
    times.append(i.text)
print(len(times))

500
500
500

In [706]:
df=pd.DataFrame({"Comments": comment, "Upvotes": upvote, "Time Stamp": times})
df

                                              Comments Upvotes    Time Stamp
0    "Life is short"\n"Girlfriend is nothing"\nMoth...      12  23 hours ago
1    SO NOW WE ALL CAN AGREE THAT THIS MAN NEVER DI...      22  23 hours ago
2               I LIKE TO WATCH THINGS I CAN'T AFFORD       10  23 hours ago
3    Moto edge 30.ultra looking dope.it can change ...      11  21 hours ago
4    Congratulations For 12 million Subscribers Giv...       9  23 hours ago
..                                                 ...     ...           ...
495  Sir  Redmi k 50 series Bharat me kis name se a...       0  23 hours ago
496                                         Stay safe        0     1 day ago
497                                          OP phones       0     1 day ago
498  Sir plz koi Kam budget me compact smartphone h...       0  22 hours ago
499  Sir kab aaega under  30000 best  ka please rep...       1     1 day ago

[500 rows x 3 columns]

In [708]:
driver.close()

#### 10. Write a python program to scrape a data for all available Hostels from https://www.hostelworld.com/ in “London” location. You have to scrape hostel name, distance from city centre, ratings, total reviews, overall reviews, privates from price, dorms from price, facilities and property description.

In [887]:
import pandas as pd
import selenium 
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
import time
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import NoSuchElementException

In [888]:
driver= webdriver.Chrome(r"C:\Users\amang\chromedriver_win32\chromedriver.exe")
driver.maximize_window()

In [889]:
#Getting url
url= "https://www.hostelworld.com/"
driver.get(url)
time.sleep(2)

In [894]:
# input in search bar
driver.find_element("xpath","/html/body/div[3]/div/div/div[1]/div[1]/div/div/div[4]/div/div[2]/div/div[1]/div/input").click()

inp=driver.find_element("xpath","/html/body/div[3]/div/div/div[1]/div[1]/div/div/div[4]/div/div[2]/div/div[1]/div/div/div/input")
inp.send_keys("London")
time.sleep(1)
driver.find_element("xpath",'/html/body/div[3]/div/div/div[1]/div[1]/div/div/div[4]/div/div[2]/div/div[1]/div/div/ul/li[2]').click()
#Search 
driver.find_element("xpath",'/html/body/div[3]/div/div/div[1]/div[1]/div/div/div[4]/div/div[2]/div/div[5]/button').click()
'''inp.send_keys(Keys.DOWN)
inp.send_keys(Keys.ENTER)'''

'inp.send_keys(Keys.DOWN)\ninp.send_keys(Keys.ENTER)'

In [895]:
#Names
name=[]
nm= driver.find_elements("xpath",'//h2[@class="title title-6"]')
for i in nm:
    name.append(i.text)
print(len(name))

30

In [896]:
#distance
dist=[]
dstnce= driver.find_elements("xpath",'//span[@class="description"]')
for i in dstnce:
    dist.append(i.text.split("- ")[1])
print(len(dist))

30

In [897]:
#Ratings, Total reviews and Overall reviews
z=[]
ratings=[]
trev=[]
orev=[]
rate= driver.find_elements("xpath",'//div[@class="bottom-rating"]')
for i in rate:
    #print (i.text.split("\n"))
    ratings.append(i.text.split("\n")[0])
    
    if (len(i.text.split("\n"))) == 3: 
        orev.append(i.text.split("\n")[1])
        z.append(i.text.split("\n")[2])
        
    else:
        orev.append("-")
        z.append(i.text.split("\n")[1])
        
for i in z:
    trev.append(i.split(" ")[0])
print(len(ratings),len(orev),len(trev))

30 30 30

In [898]:
#Price
d=[]
p=[]
dorm=[]
private=[]
pr= driver.find_elements("xpath",'//div[@class="price-col"]')
c=1
for i in pr:
    price=i.text.split('\n')
    #print(price)
    if c%2==0:
        try:
            d.append(price[1])
        except:
            d.append(price)
        
    else:
        try:
            p.append(price[1])
        except:
            p.append(price)
    c+=1
    
#Private
for i in p:
    try:
        z=(i.split(" "))
        try:
            private.append(z[1])
        except:
            private.append(z)
    except:
        private.append(i)

#dorm        
for i in d:
    try:
        z=(i.split(" "))
        try:
            dorm.append(z[1])
        except:
            dorm.append(z)
    except:
        dorm.append(i)
        
print(len(private),len(dorm))

30 30

In [901]:
link=[]

for i in range (3,len(dorm)+3):
    try:
        hotel=driver.find_element("xpath",'/html/body/div[3]/div/div/div[1]/div[4]/div/div/div['+str(i)+']/div[3]/div[1]/h2/a')
        #print("done",i)
        
    except NoSuchElementException:
        hotel=driver.find_element("xpath",'/html/body/div[3]/div/div/div[1]/div[4]/div/div/div['+str(i)+']/div[2]/div[1]/h2/a')
        #print("done",i)
        
    link.append(hotel.get_attribute("href"))
print(len(link))

30

In [978]:
description=[]
facilities=[]
for j in range (0,len(link)):
    driver.get(link[j])
    time.sleep(2)    
    
    desc=driver.find_element("xpath",'//div[@class="content collapse-content"]')
    description.append(desc.text)
    
    fac=driver.find_element("xpath",'//div[@class="facilities-container"]')
    facilities.append(fac.text)
    
print(len(description),len(facilities))

30 30

In [981]:
df=pd.DataFrame({"Hostel Name": name, "Distance from city centre": dist, "Ratings":ratings, "Total Review": trev, "Overall Review": orev, "Privates from price": private, "Dorms from price":dorm, "Facilities": facilities, "Property description": description})
df

,Hostel Name,Distance from city centre,Ratings,Total Review,Overall Review,Privates from price,Dorms from price,Facilities,Property description
0,St Christopher's Village,1.8km from city centre,8.1,11388,Fabulous,[No Privates Available],Rs3268,Facilities\nFree\nLinen Included Free City Map...,COVID 19 Policy Update.\nIn response to Corona...
1,Selina Camden,5.5km from city centre,8.6,33,Fabulous,[Rs33971],Rs8942,Facilities\nFree\nLinen Included Towels Includ...,"Among underground music venues, innovative mus..."
2,Generator London,3km from city centre,7.7,7061,Very Good,[No Privates Available],[Rs4315],Facilities\nFree\nLinen Included Free City Map...,Generator London is a design hotel-hostel loca...
3,Urbany Hostel London,5.4km from city centre,9.3,413,Superb,[Rs19884],[No Dorms Available],Facilities\nFree\nLinen Included Free WiFi\nGe...,"Welcome to Urbany Hostel London, our first int..."
4,Safestay London Elephant & Castle,1.7km from city centre,7.1,4407,Very Good,[No Privates Available],[Rs4024],Facilities\nFree\nLinen Included Free City Map...,Safestay at Elephant & Castle is ideal if you ...
5,Smart Camden Inn Hostel,4.4km from city centre,8.4,2898,Fabulous,[Rs13654],[Rs3987],Facilities\nFree\nLinen Included Free City Map...,"Located in the middle of Camden Town, we’re th..."
6,YHA London Oxford Street,2.1km from city centre,9.1,4553,Superb,[Rs12450],[No Dorms Available],Facilities\nFree\nLinen Included Free City Map...,A quiet hideaway from the bustle of the busies...
7,No.8 Seven Sisters,9km from city centre,6.2,3820,Good,[No Privates Available],[Rs2054],Facilities\nFree\nLinen Included Free WiFi\nGe...,"For Great Facilities, Comfort & Affordability ..."
8,Safestay London Kensington Holland Park,5.9km from city centre,6.5,1271,Good,[No Privates Available],[Rs3938],Facilities\nFree\nLinen Included Free WiFi\nGe...,I found this property really nice and I apprec...
9,Phoenix Hostel,4.2km from city centre,7.6,3679,Very Good,[No Privates Available],Rs4798,Facilities\nFree\nLinen Included Free City Map...,*Please note we are operating on LIMITED recep...
10,NX London Hostel,6.1km from city centre,7.3,1179,Very Good,[No Privates Available],[Rs3520],Facilities\nFree\nFree Breakfast Linen Include...,Welcome to NX London Hostel!\n\nA Friendly bac...
11,Hostel One Notting Hill,5.5km from city centre,9.2,1428,Superb,[Rs19683],[No Dorms Available],Facilities\nFree\nLinen Included Free WiFi Fre...,The perfect place for solo travelers to connec...
12,St Christopher's Hammersmith,7.5km from city centre,7.9,4075,Very Good,[No Privates Available],Rs2786,Facilities\nFree\nLinen Included Free City Map...,"In response to Coronavirus (COVID-19), additio..."
13,St Christopher's Camden,4.3km from city centre,8.4,3812,Fabulous,[No Privates Available],Rs3719,Facilities\nFree\nLinen Included Free City Map...,COVID 19 Policy Update.\nIn response to Corona...
14,London Waterloo Hostel,0.7km from city centre,6.3,2508,Good,[No Privates Available],[Rs5168],Facilities\nFree\nLinen Included Free City Map...,Note: 18-40 yrs old only.. All guest receive F...
15,"PubLove @ The White Ferry, Victoria",2.4km from city centre,8.1,271,Fabulous,[No Privates Available],[Rs6112],Facilities\nFree\nLinen Included Free City Map...,"Walk to the river, turn left, and just keep wa..."
16,St Christopher's Shepherds Bush,7km from city centre,7.4,701,Very Good,[No Privates Available],Rs2915,Facilities\nFree\nLinen Included Free City Map...,COVID 19 Policy Update.\nIn response to Corona...
17,PubLove @ The Rose & Crown,1.6km from city centre,8.0,140,Fabulous,[No Privates Available],[Rs5212],Facilities\nFree\nLinen Included Free City Map...,"Food & culture lovers, assemble!\nThe Rose & C..."
18,"PubLove @ The Crown, Battersea",4.7km from city centre,6.5,255,Good,[No Privates Available],[Rs4954],Facilities\nFree\nLinen Included Free City Map...,Do London like a local.\nStay just outside the...
19,Saint James Backpackers,5.5km from city centre,6.6,1815,Good,Rs14139,Rs4798,Facilities\nFree\nFree Breakfast Linen Include...,We are located in central London - just 5 minu...
20,"PubLove @ The Green Man, Paddington",4.3km from city centre,7.7,418,Very Good,[No Privates Available],[Rs4729],Facilities\nFree\nLinen Included Free City Map...,Where it all began - PubLove was born here in ...
21,Britannia Inn Hotel,14.5km from city centre,8.2,22,Fabulous,[Rs24771],[No Dorms Available],Facilities\nFree\nFree Breakfast Free Parking ...,The Britannia Inn Hotel is situated near the I...
22,London House Hotel,5.3km from city centre,8.8,1382,Fabulous,Rs24868,[No Dorms Available],Facilities\nFree\nFree City Maps Free WiFi\nGe...,Our lovely boutique hotel is conveniently loca...
23,Elmwood Hotel,3.2km from city centre,6.1,116,Good,[Rs16245],[No Dorms Available],Facilities\nFree\nFree Internet Access\nGenera...,We booked 2 rooms but were told by the recepti...
24,The London Home Hostel,8.2km from city centre,3.8,258,Rating,[No Privates Available],[Rs2413],Facilities\nFree\nLinen Included Free WiFi Fre...,If you are looking to meet and socialise with ...
25,Cranbrook Hotel,14.8km from city centre,No Rating,58,-,[Rs8718],[No Dorms Available],Facilities\nFree\nFree Breakfast Free Parking\...,We are located about twenty minutes by tube fr...
26,Colliers Hotel,2.1km from city centre,6.6,8,Good,[Rs11517],[No Dorms Available],Facilities\nGeneral\nKey Card Access Adaptors ...,Colliers Hotel offers basic budget accommodati...
27,City Hotel Carlton,1.8km from city centre,6.7,40,Good,[Rs11903],[No Dorms Available],Facilities\nFree\nFree Internet Access\nGenera...,good little hotel for a quick break in London....
28,Hotel Shepherds Bush London,7.6km from city centre,No Rating,0,-,Rs17309,[No Dorms Available],Facilities\nFree\nLinen Included Free City Map...,Hotel Shepherds Bush London provide 4 star hot...
29,Tony's House Hotel,4.3km from city centre,No Rating,406,-,[Rs19398],[No Dorms Available],Facilities\nFree\nFree Breakfast Free Internet...,Central London Hotel Accommodation situated in...

In [982]:
driver.close()